type PaymentHistory = {
  id: number;
  created_at: Date;
  updated_at: Date;
  uploaded_file_id: number;
  team: string;
  client_name: string;
  client_id: number;
  account_number: string;
  debtor_name: string;
  date_v1: Date;
  date_v2: Date;
  nominal_v1: number;
  nominal_v2: number;
  agent: string;
  keterangan: string;
  disc: number;
  updated_note: string;
  fee_amount: number;
};
