type Debitur = {
  id: number;
  created_at: Date;
  updated_at: Date;
  client_id: number;
  client_name: string;
  account_number: string;
  identity_number: string;
  product_type: string;
  fee: number;
  name: string;
  mobile_phone: string;
  email: string;
  address: string;
  province: string;
  gender: string;
  mariage_status: string;
  spouse_name: string;
  profession: string;
  emergency_contact: string;
  emergency_phone1: string;
  emergency_phone2: string;
  company_name: string;
  asset_desc: string;
  asset_category: string;
  license_plate: string;
  color: string;
  manufacturing_year: number;
  next_installment_number: number;
  last_paid_date: Date;
  last_paid_due_date: Date;
  due_date: Date;
  zone: string;
  tenur: number;
  branch_location: string;
  installment_amount: number;
  total_debt: number;
  remaining_debt: number;
  status: number;
  call_status: string;
  payment_status: string;
  client?: Client;
};

type DebiturAdditional = {
  id: number;
  created_at: Date;
  updated_at: Date;
  debitur_id: number;
  data: string;
  source: string;
  identifier: string;
};
